# Operators

In [1]:
import os
os.path.expanduser('~')

'C:\\Users\\Harry'

In [2]:
# Basic Python Operators
# +,-,*,/,//,%,**


In [3]:
# Arithmetic operators in Python

x = 15
y = 4

# Output: x + y = 19
print('x + y =',x+y)

# Output: x - y = 11
print('x - y =',x-y)

# Output: x * y = 60
print('x * y =',x*y)

# Output: x / y = 3.75
print('x / y =',x/y)

# Output: x // y = 3
print('x // y =',x//y)

# Output: x ** y = 50625
print('x ** y =',x**y)

x + y = 19
x - y = 11
x * y = 60
x / y = 3.75
x // y = 3
x ** y = 50625


In [4]:
# Comparison operators in Python

x = 10
y = 12

# Output: x > y is False
print('x > y  is',x>y)

# Output: x < y is True
print('x < y  is',x<y)

# Output: x == y is False
print('x == y is',x==y)

# Output: x != y is True
print('x != y is',x!=y)

# Output: x >= y is False
print('x >= y is',x>=y)

# Output: x <= y is True
print('x <= y is',x<=y)

x > y  is False
x < y  is True
x == y is False
x != y is True
x >= y is False
x <= y is True


In [5]:
# Logical operators in Python

x = True
y = False

# Output: x and y is False
print('x and y is',x and y)

# Output: x or y is True
print('x or y is',x or y)

# Output: not x is False
print('not x is',not x)

x and y is False
x or y is True
not x is False


In [6]:
# Identity operators in Python

x1 = 5
y1 = 5
x2 = 'Hello'
y2 = 'Hello'
x3 = [1,2,3]
y3 = [1,2,3]

# Output: False
print(x1 is not y1)

# Output: True
print(x2 is y2)

# Output: False
print(x3 is y3)

False
True
False


# Lists - mutable  - changable

In [7]:
list1=['harry']
for x in range(1,5):
    list1*=2
    print(list1)

['harry', 'harry']
['harry', 'harry', 'harry', 'harry']
['harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry']
['harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry']


In [8]:
list1+=['krithik']
print(list1)

['harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'krithik']


In [9]:
del list1[1:4]
print(list1)

['harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'harry', 'krithik']


# Tuples - Immutable - non changable

In [10]:
tup1=('harry','krithik')
print(tup1)

('harry', 'krithik')


# Dictionary

In [11]:
dic={"name":"Harry","age":33}
print(dic['name'])

Harry


In [12]:
print(dic['names'])

KeyError: 'names'

In [16]:
dic={}
dic['name']='Harry';
dic['age']=33
print(dic.keys())
print(dic.values())
print(dic.items())
dic['name']='who knows'
print(dic)
del dic['age']
print(dic)

dict_keys(['name', 'age'])
dict_values(['Harry', 33])
dict_items([('name', 'Harry'), ('age', 33)])
{'name': 'who knows', 'age': 33}
{'name': 'who knows'}


# Conditional statements

In [21]:
grade=60
if grade>80:
    print('Awesome')
elif grade==60:
    print('Okay okay')
elif grade>10:
    print('So what next?')
elif grade==10:
    print('Are you sick?')
else:
    print('Failed')
    

Okay okay


# Looping

In [22]:
for dicKey in dic:
    print(dicKey)


name


In [23]:
for i in range(0,15,3):
   print(i)

0
3
6
9
12


In [25]:
x = int(input('Enter a number: '))

while x != 0:
    for y in range (1, x):
        print (y)
        y+=1
        #continue
        #break
    x = int(input('Enter a number: '))
    

Enter a number: 10
1
2
3
4
5
6
7
8
9
Enter a number: 0


# Functions

In [27]:
def sameInitial(wd1, wd2):
        """Tests if two words start with the same character,  
        and returns True/False. Case distinction is ignored.""" 
        if wd1[0].lower() == wd2[0].lower(): 
            return True
        else: 
            return False
sameInitial('hello','How are you?')

True

# Functions with default arguements

In [28]:
def greet(name,msg='good mrng'):
    print(name.upper()+','+msg)
    
greet('harry')
greet('harry','Gud eve')

HARRY,good mrng
HARRY,Gud eve


# Functions with variable arguements

In [30]:
def add(*num):
    sum=0
    for i in num:
        sum+=i
    print(sum)
    return sum
add(1,2)
add(1,2,5,45,78)

3
131


131

# Import Modules

In [34]:
import random
random.randrange(1,5)

4

In [35]:
import random as r
r.randrange(1,10)

4

In [36]:
from random import randrange,randint
randrange(1,6)

5

# Open and Read Text File

In [41]:
f=open('months.txt','r')
strLine=f.readline()
f.close()
print(strLine)

January



In [43]:
f=open('months.txt','r')
for strLine in f:
    print(strLine,end='')
f.close()


January
February
March
April
May
June
July
August
September
October
November
December

In [50]:
f=open('months.txt','r')
print(f.read())
f.close()

January
February
March
April
May
June
July
August
September
October
November
December


In [51]:
# with buffer size
f=open('months.txt','r')
print(f.read(10))
f.close()

January
Fe


In [54]:
f=open('months.txt','r')
for strLine in f.readlines():
    print(strLine)
    print(strLine.strip())
f.close()

January

January
February

February
March

March
April

April
May

May
June

June
July

July
August

August
September

September
October

October
November

November
December
December


# Open and write text file

In [47]:
f=open('test.txt','w')
f.write('My first file with Python')
f.close()

In [49]:
f=open('test.txt','a')
f.write('\n\nMy second append file with Python')
f.close()

# Class

In [71]:
class Harry:
    "This is a docstring"
    def obj():
        print('inside harry function and class')

In [72]:
Harry.obj()

inside harry function and class


# Pandas => Data Wrangler 
Series(single column in dataframe) and Dataframe(excel)

In [83]:
import pandas as pd
excel=pd.read_csv('http://bit.ly/imdbratings')

In [84]:
#top 5 rows
excel.head()

star_rating                     title content_rating   genre  duration  \
0          9.3  The Shawshank Redemption              R   Crime       142   
1          9.2             The Godfather              R   Crime       175   
2          9.1    The Godfather: Part II              R   Crime       200   
3          9.0           The Dark Knight          PG-13  Action       152   
4          8.9              Pulp Fiction              R   Crime       154   

                                         actors_list  
0  [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1    [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3  [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4  [u'John Travolta', u'Uma Thurman', u'Samuel L....

In [85]:
#Last 5 rows
excel.tail()

star_rating                                            title  \
974          7.4                                          Tootsie   
975          7.4                      Back to the Future Part III   
976          7.4  Master and Commander: The Far Side of the World   
977          7.4                                      Poltergeist   
978          7.4                                      Wall Street   

    content_rating      genre  duration  \
974             PG     Comedy       116   
975             PG  Adventure       118   
976          PG-13     Action       138   
977             PG     Horror       114   
978              R      Crime       126   

                                           actors_list  
974  [u'Dustin Hoffman', u'Jessica Lange', u'Teri G...  
975  [u'Michael J. Fox', u'Christopher Lloyd', u'Ma...  
976  [u'Russell Crowe', u'Paul Bettany', u'Billy Bo...  
977  [u'JoBeth Williams', u"Heather O'Rourke", u'Cr...  
978  [u'Charlie Sheen', u'Michael Douglas', u'Tamar...

In [80]:
print(excel.columns)
print(excel.dtypes)
print(excel.shape)


Index(['star_rating', 'title', 'content_rating', 'genre', 'duration',
       'actors_list'],
      dtype='object')
star_rating       float64
title              object
content_rating     object
genre              object
duration            int64
actors_list        object
dtype: object
(979, 6)


In [79]:
print(type(excel))

<class 'pandas.core.frame.DataFrame'>


In [91]:
#subset columns
subset=excel[['star_rating', 'title']]
subset.head()

star_rating                     title
0          9.3  The Shawshank Redemption
1          9.2             The Godfather
2          9.1    The Godfather: Part II
3          9.0           The Dark Knight
4          8.9              Pulp Fiction

In [94]:
#subset columns
subset=excel[[excel.keys()[1]]]
subset.head()

title
0  The Shawshank Redemption
1             The Godfather
2    The Godfather: Part II
3           The Dark Knight
4              Pulp Fiction

# SciKit-Learn | Train and Model | Linear Classification

In [2]:
import pandas as pd
df=pd.read_csv('titanic.csv',index_col='PassengerId')
print(df.head())

             Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S

In [3]:
df = df[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Survived']]

In [4]:
df = df.dropna()

In [5]:
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

In [6]:
X = df.drop('Survived', axis=1)
y = df['Survived']

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [8]:
#Support vector machines
from sklearn.svm import SVC
model = SVC(kernel = 'linear') 

In [9]:
model

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [10]:
model.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [16]:
y_predict = model.predict(X_test)
#print(y_test)
#print(y_predict)

In [12]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_predict)

0.776536312849162

# SciKit-Learn | Scipy | Train and Model | Decision Tree Classification

In [15]:
import pandas as pd
df=pd.read_csv('titanic.csv',index_col='PassengerId')
print(df.head())

             Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S

In [17]:
df = df[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Survived']]
df = df.dropna()
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
X = df.drop('Survived', axis=1)
y = df['Survived']

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
from sklearn import tree
model=tree.DecisionTreeClassifier()

In [20]:
model

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [21]:
model.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [22]:
y_predict = model.predict(X_test)

In [23]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_predict)

0.8212290502793296

# Keras

In [1]:
#conda install -c conda-forge keras
#conda install -c conda-forge tensorflow

from keras.models import Sequential
from keras.layers import Dense
import numpy

C:\Users\Harry\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
seed = 9
numpy.random.seed(seed)

In [3]:
from pandas import read_csv
filename = 'BBCN.csv'
dataframe = read_csv(filename)
dataframe.head()

MaritalStatus  Gender  YearlyIncome  TotalChildren  NumberChildrenAtHome  \
0              5       1           9.0              2                     0   
1              5       1           6.0              3                     3   
2              5       1           6.0              3                     3   
3              5       2           7.0              0                     0   
4              5       2           8.0              5                     5   

   EnglishEducation  HouseOwnerFlag  NumberCarsOwned  CommuteDistance  Region  \
0                 5               1                0                2       2   
1                 5               0                1                1       2   
2                 5               1                1                5       2   
3                 5               0                1               10       2   
4                 5               1                4                2       2   

   Age  BikeBuyer  
0  5.0          1  
1  4.0          1  
2  4.0          1  
3  5.0          1  
4  5.0          1

In [5]:
array = dataframe.values
#Column 11 => Bike Buyer => Against which model has to be created
#X => Values until before 11
#Y => Carries only 11
X = array[:,0:11] 
Y = array[:,11]
print(X)
print(Y)

[[5. 1. 9. ... 2. 2. 5.]
 [5. 1. 6. ... 1. 2. 4.]
 [5. 1. 6. ... 5. 2. 4.]
 ...
 [3. 2. 4. ... 2. 3. 5.]
 [3. 1. 4. ... 2. 1. 4.]
 [3. 1. 4. ... 2. 1. 4.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 1. 1. 1. 0.
 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1.
 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0.
 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 1. 1. 1. 0. 1. 1. 0. 1.
 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0.
 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.
 1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1.
 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1.
 1. 1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0

In [6]:
#Creates neural network connections
model = Sequential()
model.add(Dense(12, input_dim=11, kernel_initializer='uniform', activation='relu'))
model.add(Dense(8, kernel_initializer='uniform', activation='relu'))
model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))

In [7]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [8]:
model.fit(X, Y, epochs=20, batch_size=30)

Epoch 1/20
500/500 [==============================] - 0s 919us/step - loss: 0.6931 - acc: 0.5260
Epoch 2/20
500/500 [==============================] - 0s 48us/step - loss: 0.6927 - acc: 0.5340
Epoch 3/20
500/500 [==============================] - 0s 40us/step - loss: 0.6923 - acc: 0.5340
Epoch 4/20
500/500 [==============================] - 0s 40us/step - loss: 0.6921 - acc: 0.5340
Epoch 5/20
500/500 [==============================] - 0s 48us/step - loss: 0.6916 - acc: 0.5340
Epoch 6/20
500/500 [==============================] - 0s 40us/step - loss: 0.6912 - acc: 0.5340
Epoch 7/20
500/500 [==============================] - 0s 40us/step - loss: 0.6905 - acc: 0.5340
Epoch 8/20
500/500 [==============================] - 0s 48us/step - loss: 0.6899 - acc: 0.5340
Epoch 9/20
500/500 [==============================] - 0s 40us/step - loss: 0.6891 - acc: 0.5340
Epoch 10/20
500/500 [==============================] - 0s 48us/step - loss: 0.6876 - acc: 0.5340
Epoch 11/20
500/500 [=================

In [9]:
scores = model.evaluate(X, Y)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

500/500 [==============================] - 0s 96us/step
acc: 60.20%
